title: Arya Maheshwari
description: >-
  Arya Maheshwari is an incoming PhD student in MIT EECS, affiliated with
  CSAIL and LIDS, working in theoretical computer science, machine learning,
  and game theory.
url: https://amaheshwari.com
baseurl: ""
lang: en

markdown: kramdown
permalink: pretty

exclude:
  - _archive
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
